server:
  servlet.context-path: /ymlbusy
  port: 8083
name: liyunfei
age: 25
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liyunfei?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: li159753
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
      bootstrap-servers: DESKTOP-UEBN27J:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: test
        enable-auto-commit: true
        auto-commit-interval: 1000
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
   # Redis 配置信息
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  #    password:
    timeout: 3000
    pool:
      max-active: 200
      max-wait: 1000
      max-idle: 500
      min-idle: 50
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


