package com.busy.model;

import java.io.Serializable;

public class AuthPermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_permission.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_permission.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_permission.content_type_id
     *
     * @mbg.generated
     */
    private Integer contentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_permission.codename
     *
     * @mbg.generated
     */
    private String codename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_permission.id
     *
     * @return the value of auth_permission.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_permission.id
     *
     * @param id the value for auth_permission.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_permission.name
     *
     * @return the value of auth_permission.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_permission.name
     *
     * @param name the value for auth_permission.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_permission.content_type_id
     *
     * @return the value of auth_permission.content_type_id
     *
     * @mbg.generated
     */
    public Integer getContentTypeId() {
        return contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_permission.content_type_id
     *
     * @param contentTypeId the value for auth_permission.content_type_id
     *
     * @mbg.generated
     */
    public void setContentTypeId(Integer contentTypeId) {
        this.contentTypeId = contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_permission.codename
     *
     * @return the value of auth_permission.codename
     *
     * @mbg.generated
     */
    public String getCodename() {
        return codename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_permission.codename
     *
     * @param codename the value for auth_permission.codename
     *
     * @mbg.generated
     */
    public void setCodename(String codename) {
        this.codename = codename == null ? null : codename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", contentTypeId=").append(contentTypeId);
        sb.append(", codename=").append(codename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}