package com.busy.model;

import java.io.Serializable;
import java.util.Date;

public class DjangoAdminLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.action_time
     *
     * @mbg.generated
     */
    private Date actionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.object_repr
     *
     * @mbg.generated
     */
    private String objectRepr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.action_flag
     *
     * @mbg.generated
     */
    private Short actionFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.content_type_id
     *
     * @mbg.generated
     */
    private Integer contentTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.object_id
     *
     * @mbg.generated
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_admin_log.change_message
     *
     * @mbg.generated
     */
    private String changeMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table django_admin_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.id
     *
     * @return the value of django_admin_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.id
     *
     * @param id the value for django_admin_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.action_time
     *
     * @return the value of django_admin_log.action_time
     *
     * @mbg.generated
     */
    public Date getActionTime() {
        return actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.action_time
     *
     * @param actionTime the value for django_admin_log.action_time
     *
     * @mbg.generated
     */
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.object_repr
     *
     * @return the value of django_admin_log.object_repr
     *
     * @mbg.generated
     */
    public String getObjectRepr() {
        return objectRepr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.object_repr
     *
     * @param objectRepr the value for django_admin_log.object_repr
     *
     * @mbg.generated
     */
    public void setObjectRepr(String objectRepr) {
        this.objectRepr = objectRepr == null ? null : objectRepr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.action_flag
     *
     * @return the value of django_admin_log.action_flag
     *
     * @mbg.generated
     */
    public Short getActionFlag() {
        return actionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.action_flag
     *
     * @param actionFlag the value for django_admin_log.action_flag
     *
     * @mbg.generated
     */
    public void setActionFlag(Short actionFlag) {
        this.actionFlag = actionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.content_type_id
     *
     * @return the value of django_admin_log.content_type_id
     *
     * @mbg.generated
     */
    public Integer getContentTypeId() {
        return contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.content_type_id
     *
     * @param contentTypeId the value for django_admin_log.content_type_id
     *
     * @mbg.generated
     */
    public void setContentTypeId(Integer contentTypeId) {
        this.contentTypeId = contentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.user_id
     *
     * @return the value of django_admin_log.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.user_id
     *
     * @param userId the value for django_admin_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.object_id
     *
     * @return the value of django_admin_log.object_id
     *
     * @mbg.generated
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.object_id
     *
     * @param objectId the value for django_admin_log.object_id
     *
     * @mbg.generated
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_admin_log.change_message
     *
     * @return the value of django_admin_log.change_message
     *
     * @mbg.generated
     */
    public String getChangeMessage() {
        return changeMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_admin_log.change_message
     *
     * @param changeMessage the value for django_admin_log.change_message
     *
     * @mbg.generated
     */
    public void setChangeMessage(String changeMessage) {
        this.changeMessage = changeMessage == null ? null : changeMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_admin_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", actionTime=").append(actionTime);
        sb.append(", objectRepr=").append(objectRepr);
        sb.append(", actionFlag=").append(actionFlag);
        sb.append(", contentTypeId=").append(contentTypeId);
        sb.append(", userId=").append(userId);
        sb.append(", objectId=").append(objectId);
        sb.append(", changeMessage=").append(changeMessage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}