package com.busy.model;

import java.io.Serializable;
import java.util.Date;

public class DjangoSession implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_session.session_key
     *
     * @mbg.generated
     */
    private String sessionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_session.expire_date
     *
     * @mbg.generated
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_session.session_data
     *
     * @mbg.generated
     */
    private String sessionData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table django_session
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_session.session_key
     *
     * @return the value of django_session.session_key
     *
     * @mbg.generated
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_session.session_key
     *
     * @param sessionKey the value for django_session.session_key
     *
     * @mbg.generated
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_session.expire_date
     *
     * @return the value of django_session.expire_date
     *
     * @mbg.generated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_session.expire_date
     *
     * @param expireDate the value for django_session.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_session.session_data
     *
     * @return the value of django_session.session_data
     *
     * @mbg.generated
     */
    public String getSessionData() {
        return sessionData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_session.session_data
     *
     * @param sessionData the value for django_session.session_data
     *
     * @mbg.generated
     */
    public void setSessionData(String sessionData) {
        this.sessionData = sessionData == null ? null : sessionData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_session
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sessionKey=").append(sessionKey);
        sb.append(", expireDate=").append(expireDate);
        sb.append(", sessionData=").append(sessionData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}