package com.busy.model;

import java.io.Serializable;
import java.util.Date;

public class DjangoMigrations implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_migrations.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_migrations.app
     *
     * @mbg.generated
     */
    private String app;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_migrations.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column django_migrations.applied
     *
     * @mbg.generated
     */
    private Date applied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table django_migrations
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_migrations.id
     *
     * @return the value of django_migrations.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_migrations.id
     *
     * @param id the value for django_migrations.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_migrations.app
     *
     * @return the value of django_migrations.app
     *
     * @mbg.generated
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_migrations.app
     *
     * @param app the value for django_migrations.app
     *
     * @mbg.generated
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_migrations.name
     *
     * @return the value of django_migrations.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_migrations.name
     *
     * @param name the value for django_migrations.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column django_migrations.applied
     *
     * @return the value of django_migrations.applied
     *
     * @mbg.generated
     */
    public Date getApplied() {
        return applied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column django_migrations.applied
     *
     * @param applied the value for django_migrations.applied
     *
     * @mbg.generated
     */
    public void setApplied(Date applied) {
        this.applied = applied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_migrations
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", app=").append(app);
        sb.append(", name=").append(name);
        sb.append(", applied=").append(applied);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}