package com.busy.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TQmCheckresult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.INSPECTION_ID
     *
     * @mbg.generated
     */
    private String inspectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.PROVINCE_ID
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.ACCEPT_MONTH
     *
     * @mbg.generated
     */
    private Integer acceptMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CITY_ID
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.TOUCH_ID
     *
     * @mbg.generated
     */
    private String touchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECKED_STAFF_ID
     *
     * @mbg.generated
     */
    private String checkedStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.DEPARTED_ID
     *
     * @mbg.generated
     */
    private String departedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECK_STAFF_ID
     *
     * @mbg.generated
     */
    private String checkStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.DEPART_ID
     *
     * @mbg.generated
     */
    private String departId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CRT_TIME
     *
     * @mbg.generated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.MODF_TIME
     *
     * @mbg.generated
     */
    private Date modfTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.OPR_STAFF_ID
     *
     * @mbg.generated
     */
    private String oprStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CREATE_STAFF_ID
     *
     * @mbg.generated
     */
    private String createStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.IS_DELETE
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECK_START_TIME
     *
     * @mbg.generated
     */
    private Date checkStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECK_END_TIME
     *
     * @mbg.generated
     */
    private Date checkEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECK_MODEL
     *
     * @mbg.generated
     */
    private String checkModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.WITHIN_BEYOND_FLAG
     *
     * @mbg.generated
     */
    private String withinBeyondFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.FINAL_SCORE
     *
     * @mbg.generated
     */
    private BigDecimal finalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.SCORE_TYPE
     *
     * @mbg.generated
     */
    private String scoreType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.OPERATE_TIME_LONG
     *
     * @mbg.generated
     */
    private Integer operateTimeLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.PLAY_VOICE_TIME
     *
     * @mbg.generated
     */
    private Integer playVoiceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.PLAY_VOICE_NUM
     *
     * @mbg.generated
     */
    private Integer playVoiceNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RESULT_STATUS
     *
     * @mbg.generated
     */
    private String resultStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.ERROR_RANK
     *
     * @mbg.generated
     */
    private String errorRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.BUSI_TYPE
     *
     * @mbg.generated
     */
    private String busiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECK_COMMENT
     *
     * @mbg.generated
     */
    private String checkComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.ABANDON_STATUS
     *
     * @mbg.generated
     */
    private String abandonStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.ABANDON_REASON
     *
     * @mbg.generated
     */
    private String abandonReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.ABANDON_COMMENT
     *
     * @mbg.generated
     */
    private String abandonComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.EDIT_REASON
     *
     * @mbg.generated
     */
    private String editReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.OPERATE_REASON
     *
     * @mbg.generated
     */
    private String operateReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.OPERATE_STAFF_ID
     *
     * @mbg.generated
     */
    private String operateStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.OPERATE_TYPE
     *
     * @mbg.generated
     */
    private String operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RATING_TYPE
     *
     * @mbg.generated
     */
    private String ratingType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.REMARK2
     *
     * @mbg.generated
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.R_INSPECTION_ID
     *
     * @mbg.generated
     */
    private String rInspectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CHECKTIME
     *
     * @mbg.generated
     */
    private String checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.IS_RECHECK
     *
     * @mbg.generated
     */
    private String isRecheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.PLAN_ID
     *
     * @mbg.generated
     */
    private String planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.TEMPLATE_ID
     *
     * @mbg.generated
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CASE_ID
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CASE_FLAG
     *
     * @mbg.generated
     */
    private String caseFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RECHECK_RESULT
     *
     * @mbg.generated
     */
    private String recheckResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RECHECK_REMARK
     *
     * @mbg.generated
     */
    private String recheckRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.MONITOR_FLAG
     *
     * @mbg.generated
     */
    private String monitorFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CUSTOMER_CITY
     *
     * @mbg.generated
     */
    private String customerCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.ACCEPT_NUMBER
     *
     * @mbg.generated
     */
    private String acceptNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RECORD_TIME
     *
     * @mbg.generated
     */
    private Integer recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CUSTOMER_LEVEL
     *
     * @mbg.generated
     */
    private String customerLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.DISCONTENT_REASON
     *
     * @mbg.generated
     */
    private String discontentReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CALLING_NUMBER
     *
     * @mbg.generated
     */
    private String callingNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.EXTERA_SCORE
     *
     * @mbg.generated
     */
    private Integer exteraScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.REMARK_SCORE
     *
     * @mbg.generated
     */
    private String remarkScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.HIT_FLAG
     *
     * @mbg.generated
     */
    private String hitFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.SMS_INFORM
     *
     * @mbg.generated
     */
    private Boolean smsInform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RESERVE_1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RESERVE_2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RESERVE_3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RESERVE_4
     *
     * @mbg.generated
     */
    private String reserve4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.RESERVE_5
     *
     * @mbg.generated
     */
    private String reserve5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.MODELS_NM
     *
     * @mbg.generated
     */
    private String modelsNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.CALLED_NUMBER
     *
     * @mbg.generated
     */
    private String calledNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.SPECIAL_ITEM_1
     *
     * @mbg.generated
     */
    private String specialItem1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_checkresult.SPECIAL_ITEM_2
     *
     * @mbg.generated
     */
    private String specialItem2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qm_checkresult
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.INSPECTION_ID
     *
     * @return the value of t_qm_checkresult.INSPECTION_ID
     *
     * @mbg.generated
     */
    public String getInspectionId() {
        return inspectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.INSPECTION_ID
     *
     * @param inspectionId the value for t_qm_checkresult.INSPECTION_ID
     *
     * @mbg.generated
     */
    public void setInspectionId(String inspectionId) {
        this.inspectionId = inspectionId == null ? null : inspectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.TENANT_ID
     *
     * @return the value of t_qm_checkresult.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.TENANT_ID
     *
     * @param tenantId the value for t_qm_checkresult.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.PROVINCE_ID
     *
     * @return the value of t_qm_checkresult.PROVINCE_ID
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.PROVINCE_ID
     *
     * @param provinceId the value for t_qm_checkresult.PROVINCE_ID
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.ACCEPT_MONTH
     *
     * @return the value of t_qm_checkresult.ACCEPT_MONTH
     *
     * @mbg.generated
     */
    public Integer getAcceptMonth() {
        return acceptMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.ACCEPT_MONTH
     *
     * @param acceptMonth the value for t_qm_checkresult.ACCEPT_MONTH
     *
     * @mbg.generated
     */
    public void setAcceptMonth(Integer acceptMonth) {
        this.acceptMonth = acceptMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CITY_ID
     *
     * @return the value of t_qm_checkresult.CITY_ID
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CITY_ID
     *
     * @param cityId the value for t_qm_checkresult.CITY_ID
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.TOUCH_ID
     *
     * @return the value of t_qm_checkresult.TOUCH_ID
     *
     * @mbg.generated
     */
    public String getTouchId() {
        return touchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.TOUCH_ID
     *
     * @param touchId the value for t_qm_checkresult.TOUCH_ID
     *
     * @mbg.generated
     */
    public void setTouchId(String touchId) {
        this.touchId = touchId == null ? null : touchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECKED_STAFF_ID
     *
     * @return the value of t_qm_checkresult.CHECKED_STAFF_ID
     *
     * @mbg.generated
     */
    public String getCheckedStaffId() {
        return checkedStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECKED_STAFF_ID
     *
     * @param checkedStaffId the value for t_qm_checkresult.CHECKED_STAFF_ID
     *
     * @mbg.generated
     */
    public void setCheckedStaffId(String checkedStaffId) {
        this.checkedStaffId = checkedStaffId == null ? null : checkedStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.DEPARTED_ID
     *
     * @return the value of t_qm_checkresult.DEPARTED_ID
     *
     * @mbg.generated
     */
    public String getDepartedId() {
        return departedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.DEPARTED_ID
     *
     * @param departedId the value for t_qm_checkresult.DEPARTED_ID
     *
     * @mbg.generated
     */
    public void setDepartedId(String departedId) {
        this.departedId = departedId == null ? null : departedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECK_STAFF_ID
     *
     * @return the value of t_qm_checkresult.CHECK_STAFF_ID
     *
     * @mbg.generated
     */
    public String getCheckStaffId() {
        return checkStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECK_STAFF_ID
     *
     * @param checkStaffId the value for t_qm_checkresult.CHECK_STAFF_ID
     *
     * @mbg.generated
     */
    public void setCheckStaffId(String checkStaffId) {
        this.checkStaffId = checkStaffId == null ? null : checkStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.DEPART_ID
     *
     * @return the value of t_qm_checkresult.DEPART_ID
     *
     * @mbg.generated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.DEPART_ID
     *
     * @param departId the value for t_qm_checkresult.DEPART_ID
     *
     * @mbg.generated
     */
    public void setDepartId(String departId) {
        this.departId = departId == null ? null : departId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CRT_TIME
     *
     * @return the value of t_qm_checkresult.CRT_TIME
     *
     * @mbg.generated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CRT_TIME
     *
     * @param crtTime the value for t_qm_checkresult.CRT_TIME
     *
     * @mbg.generated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.MODF_TIME
     *
     * @return the value of t_qm_checkresult.MODF_TIME
     *
     * @mbg.generated
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.MODF_TIME
     *
     * @param modfTime the value for t_qm_checkresult.MODF_TIME
     *
     * @mbg.generated
     */
    public void setModfTime(Date modfTime) {
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.OPR_STAFF_ID
     *
     * @return the value of t_qm_checkresult.OPR_STAFF_ID
     *
     * @mbg.generated
     */
    public String getOprStaffId() {
        return oprStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.OPR_STAFF_ID
     *
     * @param oprStaffId the value for t_qm_checkresult.OPR_STAFF_ID
     *
     * @mbg.generated
     */
    public void setOprStaffId(String oprStaffId) {
        this.oprStaffId = oprStaffId == null ? null : oprStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CREATE_STAFF_ID
     *
     * @return the value of t_qm_checkresult.CREATE_STAFF_ID
     *
     * @mbg.generated
     */
    public String getCreateStaffId() {
        return createStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CREATE_STAFF_ID
     *
     * @param createStaffId the value for t_qm_checkresult.CREATE_STAFF_ID
     *
     * @mbg.generated
     */
    public void setCreateStaffId(String createStaffId) {
        this.createStaffId = createStaffId == null ? null : createStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.IS_DELETE
     *
     * @return the value of t_qm_checkresult.IS_DELETE
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.IS_DELETE
     *
     * @param isDelete the value for t_qm_checkresult.IS_DELETE
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECK_START_TIME
     *
     * @return the value of t_qm_checkresult.CHECK_START_TIME
     *
     * @mbg.generated
     */
    public Date getCheckStartTime() {
        return checkStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECK_START_TIME
     *
     * @param checkStartTime the value for t_qm_checkresult.CHECK_START_TIME
     *
     * @mbg.generated
     */
    public void setCheckStartTime(Date checkStartTime) {
        this.checkStartTime = checkStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECK_END_TIME
     *
     * @return the value of t_qm_checkresult.CHECK_END_TIME
     *
     * @mbg.generated
     */
    public Date getCheckEndTime() {
        return checkEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECK_END_TIME
     *
     * @param checkEndTime the value for t_qm_checkresult.CHECK_END_TIME
     *
     * @mbg.generated
     */
    public void setCheckEndTime(Date checkEndTime) {
        this.checkEndTime = checkEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECK_MODEL
     *
     * @return the value of t_qm_checkresult.CHECK_MODEL
     *
     * @mbg.generated
     */
    public String getCheckModel() {
        return checkModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECK_MODEL
     *
     * @param checkModel the value for t_qm_checkresult.CHECK_MODEL
     *
     * @mbg.generated
     */
    public void setCheckModel(String checkModel) {
        this.checkModel = checkModel == null ? null : checkModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.WITHIN_BEYOND_FLAG
     *
     * @return the value of t_qm_checkresult.WITHIN_BEYOND_FLAG
     *
     * @mbg.generated
     */
    public String getWithinBeyondFlag() {
        return withinBeyondFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.WITHIN_BEYOND_FLAG
     *
     * @param withinBeyondFlag the value for t_qm_checkresult.WITHIN_BEYOND_FLAG
     *
     * @mbg.generated
     */
    public void setWithinBeyondFlag(String withinBeyondFlag) {
        this.withinBeyondFlag = withinBeyondFlag == null ? null : withinBeyondFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.FINAL_SCORE
     *
     * @return the value of t_qm_checkresult.FINAL_SCORE
     *
     * @mbg.generated
     */
    public BigDecimal getFinalScore() {
        return finalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.FINAL_SCORE
     *
     * @param finalScore the value for t_qm_checkresult.FINAL_SCORE
     *
     * @mbg.generated
     */
    public void setFinalScore(BigDecimal finalScore) {
        this.finalScore = finalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.SCORE_TYPE
     *
     * @return the value of t_qm_checkresult.SCORE_TYPE
     *
     * @mbg.generated
     */
    public String getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.SCORE_TYPE
     *
     * @param scoreType the value for t_qm_checkresult.SCORE_TYPE
     *
     * @mbg.generated
     */
    public void setScoreType(String scoreType) {
        this.scoreType = scoreType == null ? null : scoreType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.OPERATE_TIME_LONG
     *
     * @return the value of t_qm_checkresult.OPERATE_TIME_LONG
     *
     * @mbg.generated
     */
    public Integer getOperateTimeLong() {
        return operateTimeLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.OPERATE_TIME_LONG
     *
     * @param operateTimeLong the value for t_qm_checkresult.OPERATE_TIME_LONG
     *
     * @mbg.generated
     */
    public void setOperateTimeLong(Integer operateTimeLong) {
        this.operateTimeLong = operateTimeLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.PLAY_VOICE_TIME
     *
     * @return the value of t_qm_checkresult.PLAY_VOICE_TIME
     *
     * @mbg.generated
     */
    public Integer getPlayVoiceTime() {
        return playVoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.PLAY_VOICE_TIME
     *
     * @param playVoiceTime the value for t_qm_checkresult.PLAY_VOICE_TIME
     *
     * @mbg.generated
     */
    public void setPlayVoiceTime(Integer playVoiceTime) {
        this.playVoiceTime = playVoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.PLAY_VOICE_NUM
     *
     * @return the value of t_qm_checkresult.PLAY_VOICE_NUM
     *
     * @mbg.generated
     */
    public Integer getPlayVoiceNum() {
        return playVoiceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.PLAY_VOICE_NUM
     *
     * @param playVoiceNum the value for t_qm_checkresult.PLAY_VOICE_NUM
     *
     * @mbg.generated
     */
    public void setPlayVoiceNum(Integer playVoiceNum) {
        this.playVoiceNum = playVoiceNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RESULT_STATUS
     *
     * @return the value of t_qm_checkresult.RESULT_STATUS
     *
     * @mbg.generated
     */
    public String getResultStatus() {
        return resultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RESULT_STATUS
     *
     * @param resultStatus the value for t_qm_checkresult.RESULT_STATUS
     *
     * @mbg.generated
     */
    public void setResultStatus(String resultStatus) {
        this.resultStatus = resultStatus == null ? null : resultStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.ERROR_RANK
     *
     * @return the value of t_qm_checkresult.ERROR_RANK
     *
     * @mbg.generated
     */
    public String getErrorRank() {
        return errorRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.ERROR_RANK
     *
     * @param errorRank the value for t_qm_checkresult.ERROR_RANK
     *
     * @mbg.generated
     */
    public void setErrorRank(String errorRank) {
        this.errorRank = errorRank == null ? null : errorRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.BUSI_TYPE
     *
     * @return the value of t_qm_checkresult.BUSI_TYPE
     *
     * @mbg.generated
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.BUSI_TYPE
     *
     * @param busiType the value for t_qm_checkresult.BUSI_TYPE
     *
     * @mbg.generated
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECK_COMMENT
     *
     * @return the value of t_qm_checkresult.CHECK_COMMENT
     *
     * @mbg.generated
     */
    public String getCheckComment() {
        return checkComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECK_COMMENT
     *
     * @param checkComment the value for t_qm_checkresult.CHECK_COMMENT
     *
     * @mbg.generated
     */
    public void setCheckComment(String checkComment) {
        this.checkComment = checkComment == null ? null : checkComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.ABANDON_STATUS
     *
     * @return the value of t_qm_checkresult.ABANDON_STATUS
     *
     * @mbg.generated
     */
    public String getAbandonStatus() {
        return abandonStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.ABANDON_STATUS
     *
     * @param abandonStatus the value for t_qm_checkresult.ABANDON_STATUS
     *
     * @mbg.generated
     */
    public void setAbandonStatus(String abandonStatus) {
        this.abandonStatus = abandonStatus == null ? null : abandonStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.ABANDON_REASON
     *
     * @return the value of t_qm_checkresult.ABANDON_REASON
     *
     * @mbg.generated
     */
    public String getAbandonReason() {
        return abandonReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.ABANDON_REASON
     *
     * @param abandonReason the value for t_qm_checkresult.ABANDON_REASON
     *
     * @mbg.generated
     */
    public void setAbandonReason(String abandonReason) {
        this.abandonReason = abandonReason == null ? null : abandonReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.ABANDON_COMMENT
     *
     * @return the value of t_qm_checkresult.ABANDON_COMMENT
     *
     * @mbg.generated
     */
    public String getAbandonComment() {
        return abandonComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.ABANDON_COMMENT
     *
     * @param abandonComment the value for t_qm_checkresult.ABANDON_COMMENT
     *
     * @mbg.generated
     */
    public void setAbandonComment(String abandonComment) {
        this.abandonComment = abandonComment == null ? null : abandonComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.EDIT_REASON
     *
     * @return the value of t_qm_checkresult.EDIT_REASON
     *
     * @mbg.generated
     */
    public String getEditReason() {
        return editReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.EDIT_REASON
     *
     * @param editReason the value for t_qm_checkresult.EDIT_REASON
     *
     * @mbg.generated
     */
    public void setEditReason(String editReason) {
        this.editReason = editReason == null ? null : editReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.OPERATE_REASON
     *
     * @return the value of t_qm_checkresult.OPERATE_REASON
     *
     * @mbg.generated
     */
    public String getOperateReason() {
        return operateReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.OPERATE_REASON
     *
     * @param operateReason the value for t_qm_checkresult.OPERATE_REASON
     *
     * @mbg.generated
     */
    public void setOperateReason(String operateReason) {
        this.operateReason = operateReason == null ? null : operateReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.OPERATE_STAFF_ID
     *
     * @return the value of t_qm_checkresult.OPERATE_STAFF_ID
     *
     * @mbg.generated
     */
    public String getOperateStaffId() {
        return operateStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.OPERATE_STAFF_ID
     *
     * @param operateStaffId the value for t_qm_checkresult.OPERATE_STAFF_ID
     *
     * @mbg.generated
     */
    public void setOperateStaffId(String operateStaffId) {
        this.operateStaffId = operateStaffId == null ? null : operateStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.OPERATE_TYPE
     *
     * @return the value of t_qm_checkresult.OPERATE_TYPE
     *
     * @mbg.generated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.OPERATE_TYPE
     *
     * @param operateType the value for t_qm_checkresult.OPERATE_TYPE
     *
     * @mbg.generated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RATING_TYPE
     *
     * @return the value of t_qm_checkresult.RATING_TYPE
     *
     * @mbg.generated
     */
    public String getRatingType() {
        return ratingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RATING_TYPE
     *
     * @param ratingType the value for t_qm_checkresult.RATING_TYPE
     *
     * @mbg.generated
     */
    public void setRatingType(String ratingType) {
        this.ratingType = ratingType == null ? null : ratingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.REMARK
     *
     * @return the value of t_qm_checkresult.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.REMARK
     *
     * @param remark the value for t_qm_checkresult.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.REMARK2
     *
     * @return the value of t_qm_checkresult.REMARK2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.REMARK2
     *
     * @param remark2 the value for t_qm_checkresult.REMARK2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.R_INSPECTION_ID
     *
     * @return the value of t_qm_checkresult.R_INSPECTION_ID
     *
     * @mbg.generated
     */
    public String getrInspectionId() {
        return rInspectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.R_INSPECTION_ID
     *
     * @param rInspectionId the value for t_qm_checkresult.R_INSPECTION_ID
     *
     * @mbg.generated
     */
    public void setrInspectionId(String rInspectionId) {
        this.rInspectionId = rInspectionId == null ? null : rInspectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CHECKTIME
     *
     * @return the value of t_qm_checkresult.CHECKTIME
     *
     * @mbg.generated
     */
    public String getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CHECKTIME
     *
     * @param checktime the value for t_qm_checkresult.CHECKTIME
     *
     * @mbg.generated
     */
    public void setChecktime(String checktime) {
        this.checktime = checktime == null ? null : checktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.IS_RECHECK
     *
     * @return the value of t_qm_checkresult.IS_RECHECK
     *
     * @mbg.generated
     */
    public String getIsRecheck() {
        return isRecheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.IS_RECHECK
     *
     * @param isRecheck the value for t_qm_checkresult.IS_RECHECK
     *
     * @mbg.generated
     */
    public void setIsRecheck(String isRecheck) {
        this.isRecheck = isRecheck == null ? null : isRecheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.PLAN_ID
     *
     * @return the value of t_qm_checkresult.PLAN_ID
     *
     * @mbg.generated
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.PLAN_ID
     *
     * @param planId the value for t_qm_checkresult.PLAN_ID
     *
     * @mbg.generated
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.TEMPLATE_ID
     *
     * @return the value of t_qm_checkresult.TEMPLATE_ID
     *
     * @mbg.generated
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.TEMPLATE_ID
     *
     * @param templateId the value for t_qm_checkresult.TEMPLATE_ID
     *
     * @mbg.generated
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CASE_ID
     *
     * @return the value of t_qm_checkresult.CASE_ID
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CASE_ID
     *
     * @param caseId the value for t_qm_checkresult.CASE_ID
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CASE_FLAG
     *
     * @return the value of t_qm_checkresult.CASE_FLAG
     *
     * @mbg.generated
     */
    public String getCaseFlag() {
        return caseFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CASE_FLAG
     *
     * @param caseFlag the value for t_qm_checkresult.CASE_FLAG
     *
     * @mbg.generated
     */
    public void setCaseFlag(String caseFlag) {
        this.caseFlag = caseFlag == null ? null : caseFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RECHECK_RESULT
     *
     * @return the value of t_qm_checkresult.RECHECK_RESULT
     *
     * @mbg.generated
     */
    public String getRecheckResult() {
        return recheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RECHECK_RESULT
     *
     * @param recheckResult the value for t_qm_checkresult.RECHECK_RESULT
     *
     * @mbg.generated
     */
    public void setRecheckResult(String recheckResult) {
        this.recheckResult = recheckResult == null ? null : recheckResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RECHECK_REMARK
     *
     * @return the value of t_qm_checkresult.RECHECK_REMARK
     *
     * @mbg.generated
     */
    public String getRecheckRemark() {
        return recheckRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RECHECK_REMARK
     *
     * @param recheckRemark the value for t_qm_checkresult.RECHECK_REMARK
     *
     * @mbg.generated
     */
    public void setRecheckRemark(String recheckRemark) {
        this.recheckRemark = recheckRemark == null ? null : recheckRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.MONITOR_FLAG
     *
     * @return the value of t_qm_checkresult.MONITOR_FLAG
     *
     * @mbg.generated
     */
    public String getMonitorFlag() {
        return monitorFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.MONITOR_FLAG
     *
     * @param monitorFlag the value for t_qm_checkresult.MONITOR_FLAG
     *
     * @mbg.generated
     */
    public void setMonitorFlag(String monitorFlag) {
        this.monitorFlag = monitorFlag == null ? null : monitorFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CUSTOMER_CITY
     *
     * @return the value of t_qm_checkresult.CUSTOMER_CITY
     *
     * @mbg.generated
     */
    public String getCustomerCity() {
        return customerCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CUSTOMER_CITY
     *
     * @param customerCity the value for t_qm_checkresult.CUSTOMER_CITY
     *
     * @mbg.generated
     */
    public void setCustomerCity(String customerCity) {
        this.customerCity = customerCity == null ? null : customerCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.ACCEPT_NUMBER
     *
     * @return the value of t_qm_checkresult.ACCEPT_NUMBER
     *
     * @mbg.generated
     */
    public String getAcceptNumber() {
        return acceptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.ACCEPT_NUMBER
     *
     * @param acceptNumber the value for t_qm_checkresult.ACCEPT_NUMBER
     *
     * @mbg.generated
     */
    public void setAcceptNumber(String acceptNumber) {
        this.acceptNumber = acceptNumber == null ? null : acceptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RECORD_TIME
     *
     * @return the value of t_qm_checkresult.RECORD_TIME
     *
     * @mbg.generated
     */
    public Integer getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RECORD_TIME
     *
     * @param recordTime the value for t_qm_checkresult.RECORD_TIME
     *
     * @mbg.generated
     */
    public void setRecordTime(Integer recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CUSTOMER_LEVEL
     *
     * @return the value of t_qm_checkresult.CUSTOMER_LEVEL
     *
     * @mbg.generated
     */
    public String getCustomerLevel() {
        return customerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CUSTOMER_LEVEL
     *
     * @param customerLevel the value for t_qm_checkresult.CUSTOMER_LEVEL
     *
     * @mbg.generated
     */
    public void setCustomerLevel(String customerLevel) {
        this.customerLevel = customerLevel == null ? null : customerLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.DISCONTENT_REASON
     *
     * @return the value of t_qm_checkresult.DISCONTENT_REASON
     *
     * @mbg.generated
     */
    public String getDiscontentReason() {
        return discontentReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.DISCONTENT_REASON
     *
     * @param discontentReason the value for t_qm_checkresult.DISCONTENT_REASON
     *
     * @mbg.generated
     */
    public void setDiscontentReason(String discontentReason) {
        this.discontentReason = discontentReason == null ? null : discontentReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CALLING_NUMBER
     *
     * @return the value of t_qm_checkresult.CALLING_NUMBER
     *
     * @mbg.generated
     */
    public String getCallingNumber() {
        return callingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CALLING_NUMBER
     *
     * @param callingNumber the value for t_qm_checkresult.CALLING_NUMBER
     *
     * @mbg.generated
     */
    public void setCallingNumber(String callingNumber) {
        this.callingNumber = callingNumber == null ? null : callingNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.EXTERA_SCORE
     *
     * @return the value of t_qm_checkresult.EXTERA_SCORE
     *
     * @mbg.generated
     */
    public Integer getExteraScore() {
        return exteraScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.EXTERA_SCORE
     *
     * @param exteraScore the value for t_qm_checkresult.EXTERA_SCORE
     *
     * @mbg.generated
     */
    public void setExteraScore(Integer exteraScore) {
        this.exteraScore = exteraScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.REMARK_SCORE
     *
     * @return the value of t_qm_checkresult.REMARK_SCORE
     *
     * @mbg.generated
     */
    public String getRemarkScore() {
        return remarkScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.REMARK_SCORE
     *
     * @param remarkScore the value for t_qm_checkresult.REMARK_SCORE
     *
     * @mbg.generated
     */
    public void setRemarkScore(String remarkScore) {
        this.remarkScore = remarkScore == null ? null : remarkScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.HIT_FLAG
     *
     * @return the value of t_qm_checkresult.HIT_FLAG
     *
     * @mbg.generated
     */
    public String getHitFlag() {
        return hitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.HIT_FLAG
     *
     * @param hitFlag the value for t_qm_checkresult.HIT_FLAG
     *
     * @mbg.generated
     */
    public void setHitFlag(String hitFlag) {
        this.hitFlag = hitFlag == null ? null : hitFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.SMS_INFORM
     *
     * @return the value of t_qm_checkresult.SMS_INFORM
     *
     * @mbg.generated
     */
    public Boolean getSmsInform() {
        return smsInform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.SMS_INFORM
     *
     * @param smsInform the value for t_qm_checkresult.SMS_INFORM
     *
     * @mbg.generated
     */
    public void setSmsInform(Boolean smsInform) {
        this.smsInform = smsInform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RESERVE_1
     *
     * @return the value of t_qm_checkresult.RESERVE_1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RESERVE_1
     *
     * @param reserve1 the value for t_qm_checkresult.RESERVE_1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RESERVE_2
     *
     * @return the value of t_qm_checkresult.RESERVE_2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RESERVE_2
     *
     * @param reserve2 the value for t_qm_checkresult.RESERVE_2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RESERVE_3
     *
     * @return the value of t_qm_checkresult.RESERVE_3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RESERVE_3
     *
     * @param reserve3 the value for t_qm_checkresult.RESERVE_3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RESERVE_4
     *
     * @return the value of t_qm_checkresult.RESERVE_4
     *
     * @mbg.generated
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RESERVE_4
     *
     * @param reserve4 the value for t_qm_checkresult.RESERVE_4
     *
     * @mbg.generated
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.RESERVE_5
     *
     * @return the value of t_qm_checkresult.RESERVE_5
     *
     * @mbg.generated
     */
    public String getReserve5() {
        return reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.RESERVE_5
     *
     * @param reserve5 the value for t_qm_checkresult.RESERVE_5
     *
     * @mbg.generated
     */
    public void setReserve5(String reserve5) {
        this.reserve5 = reserve5 == null ? null : reserve5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.MODELS_NM
     *
     * @return the value of t_qm_checkresult.MODELS_NM
     *
     * @mbg.generated
     */
    public String getModelsNm() {
        return modelsNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.MODELS_NM
     *
     * @param modelsNm the value for t_qm_checkresult.MODELS_NM
     *
     * @mbg.generated
     */
    public void setModelsNm(String modelsNm) {
        this.modelsNm = modelsNm == null ? null : modelsNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.CALLED_NUMBER
     *
     * @return the value of t_qm_checkresult.CALLED_NUMBER
     *
     * @mbg.generated
     */
    public String getCalledNumber() {
        return calledNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.CALLED_NUMBER
     *
     * @param calledNumber the value for t_qm_checkresult.CALLED_NUMBER
     *
     * @mbg.generated
     */
    public void setCalledNumber(String calledNumber) {
        this.calledNumber = calledNumber == null ? null : calledNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.SPECIAL_ITEM_1
     *
     * @return the value of t_qm_checkresult.SPECIAL_ITEM_1
     *
     * @mbg.generated
     */
    public String getSpecialItem1() {
        return specialItem1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.SPECIAL_ITEM_1
     *
     * @param specialItem1 the value for t_qm_checkresult.SPECIAL_ITEM_1
     *
     * @mbg.generated
     */
    public void setSpecialItem1(String specialItem1) {
        this.specialItem1 = specialItem1 == null ? null : specialItem1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_checkresult.SPECIAL_ITEM_2
     *
     * @return the value of t_qm_checkresult.SPECIAL_ITEM_2
     *
     * @mbg.generated
     */
    public String getSpecialItem2() {
        return specialItem2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_checkresult.SPECIAL_ITEM_2
     *
     * @param specialItem2 the value for t_qm_checkresult.SPECIAL_ITEM_2
     *
     * @mbg.generated
     */
    public void setSpecialItem2(String specialItem2) {
        this.specialItem2 = specialItem2 == null ? null : specialItem2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_checkresult
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inspectionId=").append(inspectionId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", acceptMonth=").append(acceptMonth);
        sb.append(", cityId=").append(cityId);
        sb.append(", touchId=").append(touchId);
        sb.append(", checkedStaffId=").append(checkedStaffId);
        sb.append(", departedId=").append(departedId);
        sb.append(", checkStaffId=").append(checkStaffId);
        sb.append(", departId=").append(departId);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", modfTime=").append(modfTime);
        sb.append(", oprStaffId=").append(oprStaffId);
        sb.append(", createStaffId=").append(createStaffId);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", checkStartTime=").append(checkStartTime);
        sb.append(", checkEndTime=").append(checkEndTime);
        sb.append(", checkModel=").append(checkModel);
        sb.append(", withinBeyondFlag=").append(withinBeyondFlag);
        sb.append(", finalScore=").append(finalScore);
        sb.append(", scoreType=").append(scoreType);
        sb.append(", operateTimeLong=").append(operateTimeLong);
        sb.append(", playVoiceTime=").append(playVoiceTime);
        sb.append(", playVoiceNum=").append(playVoiceNum);
        sb.append(", resultStatus=").append(resultStatus);
        sb.append(", errorRank=").append(errorRank);
        sb.append(", busiType=").append(busiType);
        sb.append(", checkComment=").append(checkComment);
        sb.append(", abandonStatus=").append(abandonStatus);
        sb.append(", abandonReason=").append(abandonReason);
        sb.append(", abandonComment=").append(abandonComment);
        sb.append(", editReason=").append(editReason);
        sb.append(", operateReason=").append(operateReason);
        sb.append(", operateStaffId=").append(operateStaffId);
        sb.append(", operateType=").append(operateType);
        sb.append(", ratingType=").append(ratingType);
        sb.append(", remark=").append(remark);
        sb.append(", remark2=").append(remark2);
        sb.append(", rInspectionId=").append(rInspectionId);
        sb.append(", checktime=").append(checktime);
        sb.append(", isRecheck=").append(isRecheck);
        sb.append(", planId=").append(planId);
        sb.append(", templateId=").append(templateId);
        sb.append(", caseId=").append(caseId);
        sb.append(", caseFlag=").append(caseFlag);
        sb.append(", recheckResult=").append(recheckResult);
        sb.append(", recheckRemark=").append(recheckRemark);
        sb.append(", monitorFlag=").append(monitorFlag);
        sb.append(", customerCity=").append(customerCity);
        sb.append(", acceptNumber=").append(acceptNumber);
        sb.append(", recordTime=").append(recordTime);
        sb.append(", customerLevel=").append(customerLevel);
        sb.append(", discontentReason=").append(discontentReason);
        sb.append(", callingNumber=").append(callingNumber);
        sb.append(", exteraScore=").append(exteraScore);
        sb.append(", remarkScore=").append(remarkScore);
        sb.append(", hitFlag=").append(hitFlag);
        sb.append(", smsInform=").append(smsInform);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", reserve4=").append(reserve4);
        sb.append(", reserve5=").append(reserve5);
        sb.append(", modelsNm=").append(modelsNm);
        sb.append(", calledNumber=").append(calledNumber);
        sb.append(", specialItem1=").append(specialItem1);
        sb.append(", specialItem2=").append(specialItem2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}