package com.busy.model;

import java.io.Serializable;
import java.util.Date;

public class TQmTransChangeRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.PROVINCE_ID
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.CRT_TIME
     *
     * @mbg.generated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.OP_STAFF_ID
     *
     * @mbg.generated
     */
    private String opStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.OP_STAFF_NAME
     *
     * @mbg.generated
     */
    private String opStaffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.op_type
     *
     * @mbg.generated
     */
    private String opType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.BEFORE_TRANS_PERC
     *
     * @mbg.generated
     */
    private String beforeTransPerc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.BEFORE_TRANS_DAY
     *
     * @mbg.generated
     */
    private String beforeTransDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.BEFORE_TRANS_THRESHOLD
     *
     * @mbg.generated
     */
    private String beforeTransThreshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.TRANS_PERC_CHANGE
     *
     * @mbg.generated
     */
    private String transPercChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.TRANS_DAY_CHANGE
     *
     * @mbg.generated
     */
    private String transDayChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.TRANS_THRESHOLD_CHANGE
     *
     * @mbg.generated
     */
    private String transThresholdChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.BEFORE_TRANS_TYPE
     *
     * @mbg.generated
     */
    private String beforeTransType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.TRANS_TYPE
     *
     * @mbg.generated
     */
    private String transType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.RESERVE_1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.RESERVE_2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.RESERVE_3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.RESERVE_4
     *
     * @mbg.generated
     */
    private String reserve4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_trans_change_record.RESERVE_5
     *
     * @mbg.generated
     */
    private String reserve5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.ID
     *
     * @return the value of t_qm_trans_change_record.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.ID
     *
     * @param id the value for t_qm_trans_change_record.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.PROVINCE_ID
     *
     * @return the value of t_qm_trans_change_record.PROVINCE_ID
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.PROVINCE_ID
     *
     * @param provinceId the value for t_qm_trans_change_record.PROVINCE_ID
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.CRT_TIME
     *
     * @return the value of t_qm_trans_change_record.CRT_TIME
     *
     * @mbg.generated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.CRT_TIME
     *
     * @param crtTime the value for t_qm_trans_change_record.CRT_TIME
     *
     * @mbg.generated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.OP_STAFF_ID
     *
     * @return the value of t_qm_trans_change_record.OP_STAFF_ID
     *
     * @mbg.generated
     */
    public String getOpStaffId() {
        return opStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.OP_STAFF_ID
     *
     * @param opStaffId the value for t_qm_trans_change_record.OP_STAFF_ID
     *
     * @mbg.generated
     */
    public void setOpStaffId(String opStaffId) {
        this.opStaffId = opStaffId == null ? null : opStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.OP_STAFF_NAME
     *
     * @return the value of t_qm_trans_change_record.OP_STAFF_NAME
     *
     * @mbg.generated
     */
    public String getOpStaffName() {
        return opStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.OP_STAFF_NAME
     *
     * @param opStaffName the value for t_qm_trans_change_record.OP_STAFF_NAME
     *
     * @mbg.generated
     */
    public void setOpStaffName(String opStaffName) {
        this.opStaffName = opStaffName == null ? null : opStaffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.op_type
     *
     * @return the value of t_qm_trans_change_record.op_type
     *
     * @mbg.generated
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.op_type
     *
     * @param opType the value for t_qm_trans_change_record.op_type
     *
     * @mbg.generated
     */
    public void setOpType(String opType) {
        this.opType = opType == null ? null : opType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.BEFORE_TRANS_PERC
     *
     * @return the value of t_qm_trans_change_record.BEFORE_TRANS_PERC
     *
     * @mbg.generated
     */
    public String getBeforeTransPerc() {
        return beforeTransPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.BEFORE_TRANS_PERC
     *
     * @param beforeTransPerc the value for t_qm_trans_change_record.BEFORE_TRANS_PERC
     *
     * @mbg.generated
     */
    public void setBeforeTransPerc(String beforeTransPerc) {
        this.beforeTransPerc = beforeTransPerc == null ? null : beforeTransPerc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.BEFORE_TRANS_DAY
     *
     * @return the value of t_qm_trans_change_record.BEFORE_TRANS_DAY
     *
     * @mbg.generated
     */
    public String getBeforeTransDay() {
        return beforeTransDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.BEFORE_TRANS_DAY
     *
     * @param beforeTransDay the value for t_qm_trans_change_record.BEFORE_TRANS_DAY
     *
     * @mbg.generated
     */
    public void setBeforeTransDay(String beforeTransDay) {
        this.beforeTransDay = beforeTransDay == null ? null : beforeTransDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.BEFORE_TRANS_THRESHOLD
     *
     * @return the value of t_qm_trans_change_record.BEFORE_TRANS_THRESHOLD
     *
     * @mbg.generated
     */
    public String getBeforeTransThreshold() {
        return beforeTransThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.BEFORE_TRANS_THRESHOLD
     *
     * @param beforeTransThreshold the value for t_qm_trans_change_record.BEFORE_TRANS_THRESHOLD
     *
     * @mbg.generated
     */
    public void setBeforeTransThreshold(String beforeTransThreshold) {
        this.beforeTransThreshold = beforeTransThreshold == null ? null : beforeTransThreshold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.TRANS_PERC_CHANGE
     *
     * @return the value of t_qm_trans_change_record.TRANS_PERC_CHANGE
     *
     * @mbg.generated
     */
    public String getTransPercChange() {
        return transPercChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.TRANS_PERC_CHANGE
     *
     * @param transPercChange the value for t_qm_trans_change_record.TRANS_PERC_CHANGE
     *
     * @mbg.generated
     */
    public void setTransPercChange(String transPercChange) {
        this.transPercChange = transPercChange == null ? null : transPercChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.TRANS_DAY_CHANGE
     *
     * @return the value of t_qm_trans_change_record.TRANS_DAY_CHANGE
     *
     * @mbg.generated
     */
    public String getTransDayChange() {
        return transDayChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.TRANS_DAY_CHANGE
     *
     * @param transDayChange the value for t_qm_trans_change_record.TRANS_DAY_CHANGE
     *
     * @mbg.generated
     */
    public void setTransDayChange(String transDayChange) {
        this.transDayChange = transDayChange == null ? null : transDayChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.TRANS_THRESHOLD_CHANGE
     *
     * @return the value of t_qm_trans_change_record.TRANS_THRESHOLD_CHANGE
     *
     * @mbg.generated
     */
    public String getTransThresholdChange() {
        return transThresholdChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.TRANS_THRESHOLD_CHANGE
     *
     * @param transThresholdChange the value for t_qm_trans_change_record.TRANS_THRESHOLD_CHANGE
     *
     * @mbg.generated
     */
    public void setTransThresholdChange(String transThresholdChange) {
        this.transThresholdChange = transThresholdChange == null ? null : transThresholdChange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.BEFORE_TRANS_TYPE
     *
     * @return the value of t_qm_trans_change_record.BEFORE_TRANS_TYPE
     *
     * @mbg.generated
     */
    public String getBeforeTransType() {
        return beforeTransType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.BEFORE_TRANS_TYPE
     *
     * @param beforeTransType the value for t_qm_trans_change_record.BEFORE_TRANS_TYPE
     *
     * @mbg.generated
     */
    public void setBeforeTransType(String beforeTransType) {
        this.beforeTransType = beforeTransType == null ? null : beforeTransType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.TRANS_TYPE
     *
     * @return the value of t_qm_trans_change_record.TRANS_TYPE
     *
     * @mbg.generated
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.TRANS_TYPE
     *
     * @param transType the value for t_qm_trans_change_record.TRANS_TYPE
     *
     * @mbg.generated
     */
    public void setTransType(String transType) {
        this.transType = transType == null ? null : transType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.RESERVE_1
     *
     * @return the value of t_qm_trans_change_record.RESERVE_1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.RESERVE_1
     *
     * @param reserve1 the value for t_qm_trans_change_record.RESERVE_1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.RESERVE_2
     *
     * @return the value of t_qm_trans_change_record.RESERVE_2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.RESERVE_2
     *
     * @param reserve2 the value for t_qm_trans_change_record.RESERVE_2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.RESERVE_3
     *
     * @return the value of t_qm_trans_change_record.RESERVE_3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.RESERVE_3
     *
     * @param reserve3 the value for t_qm_trans_change_record.RESERVE_3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.RESERVE_4
     *
     * @return the value of t_qm_trans_change_record.RESERVE_4
     *
     * @mbg.generated
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.RESERVE_4
     *
     * @param reserve4 the value for t_qm_trans_change_record.RESERVE_4
     *
     * @mbg.generated
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_trans_change_record.RESERVE_5
     *
     * @return the value of t_qm_trans_change_record.RESERVE_5
     *
     * @mbg.generated
     */
    public String getReserve5() {
        return reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_trans_change_record.RESERVE_5
     *
     * @param reserve5 the value for t_qm_trans_change_record.RESERVE_5
     *
     * @mbg.generated
     */
    public void setReserve5(String reserve5) {
        this.reserve5 = reserve5 == null ? null : reserve5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", opStaffId=").append(opStaffId);
        sb.append(", opStaffName=").append(opStaffName);
        sb.append(", opType=").append(opType);
        sb.append(", beforeTransPerc=").append(beforeTransPerc);
        sb.append(", beforeTransDay=").append(beforeTransDay);
        sb.append(", beforeTransThreshold=").append(beforeTransThreshold);
        sb.append(", transPercChange=").append(transPercChange);
        sb.append(", transDayChange=").append(transDayChange);
        sb.append(", transThresholdChange=").append(transThresholdChange);
        sb.append(", beforeTransType=").append(beforeTransType);
        sb.append(", transType=").append(transType);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", reserve4=").append(reserve4);
        sb.append(", reserve5=").append(reserve5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}