package com.busy.model;

import java.io.Serializable;
import java.util.Date;

public class TQmTemplatedetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.NODE_ID
     *
     * @mbg.generated
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.NODE_TYPE
     *
     * @mbg.generated
     */
    private String nodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.TEMPLATE_ID
     *
     * @mbg.generated
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.TENANT_ID
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.PROVINCE_ID
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.CITY_ID
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.NODE_NAME
     *
     * @mbg.generated
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.P_NODE_ID
     *
     * @mbg.generated
     */
    private String pNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.NODE_STRUCT
     *
     * @mbg.generated
     */
    private String nodeStruct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.MINUS_SCORE
     *
     * @mbg.generated
     */
    private Integer minusScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.Deduct_range
     *
     * @mbg.generated
     */
    private String deductRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.NODE_ORDER
     *
     * @mbg.generated
     */
    private Integer nodeOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.CRT_TIME
     *
     * @mbg.generated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.MODF_TIME
     *
     * @mbg.generated
     */
    private Date modfTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.OPR_STAFF_ID
     *
     * @mbg.generated
     */
    private String oprStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.CREATE_STAFF_ID
     *
     * @mbg.generated
     */
    private String createStaffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.IS_DELETE
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.PERC_SCORE
     *
     * @mbg.generated
     */
    private Integer percScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.RESERVE_1
     *
     * @mbg.generated
     */
    private String reserve1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.RESERVE_2
     *
     * @mbg.generated
     */
    private String reserve2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.RESERVE_3
     *
     * @mbg.generated
     */
    private String reserve3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.RESERVE_4
     *
     * @mbg.generated
     */
    private String reserve4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_qm_templatedetail.RESERVE_5
     *
     * @mbg.generated
     */
    private String reserve5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_qm_templatedetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.ID
     *
     * @return the value of t_qm_templatedetail.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.ID
     *
     * @param id the value for t_qm_templatedetail.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.NODE_ID
     *
     * @return the value of t_qm_templatedetail.NODE_ID
     *
     * @mbg.generated
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.NODE_ID
     *
     * @param nodeId the value for t_qm_templatedetail.NODE_ID
     *
     * @mbg.generated
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.NODE_TYPE
     *
     * @return the value of t_qm_templatedetail.NODE_TYPE
     *
     * @mbg.generated
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.NODE_TYPE
     *
     * @param nodeType the value for t_qm_templatedetail.NODE_TYPE
     *
     * @mbg.generated
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.TEMPLATE_ID
     *
     * @return the value of t_qm_templatedetail.TEMPLATE_ID
     *
     * @mbg.generated
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.TEMPLATE_ID
     *
     * @param templateId the value for t_qm_templatedetail.TEMPLATE_ID
     *
     * @mbg.generated
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.TENANT_ID
     *
     * @return the value of t_qm_templatedetail.TENANT_ID
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.TENANT_ID
     *
     * @param tenantId the value for t_qm_templatedetail.TENANT_ID
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.PROVINCE_ID
     *
     * @return the value of t_qm_templatedetail.PROVINCE_ID
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.PROVINCE_ID
     *
     * @param provinceId the value for t_qm_templatedetail.PROVINCE_ID
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.CITY_ID
     *
     * @return the value of t_qm_templatedetail.CITY_ID
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.CITY_ID
     *
     * @param cityId the value for t_qm_templatedetail.CITY_ID
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.NODE_NAME
     *
     * @return the value of t_qm_templatedetail.NODE_NAME
     *
     * @mbg.generated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.NODE_NAME
     *
     * @param nodeName the value for t_qm_templatedetail.NODE_NAME
     *
     * @mbg.generated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.P_NODE_ID
     *
     * @return the value of t_qm_templatedetail.P_NODE_ID
     *
     * @mbg.generated
     */
    public String getpNodeId() {
        return pNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.P_NODE_ID
     *
     * @param pNodeId the value for t_qm_templatedetail.P_NODE_ID
     *
     * @mbg.generated
     */
    public void setpNodeId(String pNodeId) {
        this.pNodeId = pNodeId == null ? null : pNodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.NODE_STRUCT
     *
     * @return the value of t_qm_templatedetail.NODE_STRUCT
     *
     * @mbg.generated
     */
    public String getNodeStruct() {
        return nodeStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.NODE_STRUCT
     *
     * @param nodeStruct the value for t_qm_templatedetail.NODE_STRUCT
     *
     * @mbg.generated
     */
    public void setNodeStruct(String nodeStruct) {
        this.nodeStruct = nodeStruct == null ? null : nodeStruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.MINUS_SCORE
     *
     * @return the value of t_qm_templatedetail.MINUS_SCORE
     *
     * @mbg.generated
     */
    public Integer getMinusScore() {
        return minusScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.MINUS_SCORE
     *
     * @param minusScore the value for t_qm_templatedetail.MINUS_SCORE
     *
     * @mbg.generated
     */
    public void setMinusScore(Integer minusScore) {
        this.minusScore = minusScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.Deduct_range
     *
     * @return the value of t_qm_templatedetail.Deduct_range
     *
     * @mbg.generated
     */
    public String getDeductRange() {
        return deductRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.Deduct_range
     *
     * @param deductRange the value for t_qm_templatedetail.Deduct_range
     *
     * @mbg.generated
     */
    public void setDeductRange(String deductRange) {
        this.deductRange = deductRange == null ? null : deductRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.REMARK
     *
     * @return the value of t_qm_templatedetail.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.REMARK
     *
     * @param remark the value for t_qm_templatedetail.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.NODE_ORDER
     *
     * @return the value of t_qm_templatedetail.NODE_ORDER
     *
     * @mbg.generated
     */
    public Integer getNodeOrder() {
        return nodeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.NODE_ORDER
     *
     * @param nodeOrder the value for t_qm_templatedetail.NODE_ORDER
     *
     * @mbg.generated
     */
    public void setNodeOrder(Integer nodeOrder) {
        this.nodeOrder = nodeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.CRT_TIME
     *
     * @return the value of t_qm_templatedetail.CRT_TIME
     *
     * @mbg.generated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.CRT_TIME
     *
     * @param crtTime the value for t_qm_templatedetail.CRT_TIME
     *
     * @mbg.generated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.MODF_TIME
     *
     * @return the value of t_qm_templatedetail.MODF_TIME
     *
     * @mbg.generated
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.MODF_TIME
     *
     * @param modfTime the value for t_qm_templatedetail.MODF_TIME
     *
     * @mbg.generated
     */
    public void setModfTime(Date modfTime) {
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.OPR_STAFF_ID
     *
     * @return the value of t_qm_templatedetail.OPR_STAFF_ID
     *
     * @mbg.generated
     */
    public String getOprStaffId() {
        return oprStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.OPR_STAFF_ID
     *
     * @param oprStaffId the value for t_qm_templatedetail.OPR_STAFF_ID
     *
     * @mbg.generated
     */
    public void setOprStaffId(String oprStaffId) {
        this.oprStaffId = oprStaffId == null ? null : oprStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.CREATE_STAFF_ID
     *
     * @return the value of t_qm_templatedetail.CREATE_STAFF_ID
     *
     * @mbg.generated
     */
    public String getCreateStaffId() {
        return createStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.CREATE_STAFF_ID
     *
     * @param createStaffId the value for t_qm_templatedetail.CREATE_STAFF_ID
     *
     * @mbg.generated
     */
    public void setCreateStaffId(String createStaffId) {
        this.createStaffId = createStaffId == null ? null : createStaffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.IS_DELETE
     *
     * @return the value of t_qm_templatedetail.IS_DELETE
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.IS_DELETE
     *
     * @param isDelete the value for t_qm_templatedetail.IS_DELETE
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.PERC_SCORE
     *
     * @return the value of t_qm_templatedetail.PERC_SCORE
     *
     * @mbg.generated
     */
    public Integer getPercScore() {
        return percScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.PERC_SCORE
     *
     * @param percScore the value for t_qm_templatedetail.PERC_SCORE
     *
     * @mbg.generated
     */
    public void setPercScore(Integer percScore) {
        this.percScore = percScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.RESERVE_1
     *
     * @return the value of t_qm_templatedetail.RESERVE_1
     *
     * @mbg.generated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.RESERVE_1
     *
     * @param reserve1 the value for t_qm_templatedetail.RESERVE_1
     *
     * @mbg.generated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.RESERVE_2
     *
     * @return the value of t_qm_templatedetail.RESERVE_2
     *
     * @mbg.generated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.RESERVE_2
     *
     * @param reserve2 the value for t_qm_templatedetail.RESERVE_2
     *
     * @mbg.generated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.RESERVE_3
     *
     * @return the value of t_qm_templatedetail.RESERVE_3
     *
     * @mbg.generated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.RESERVE_3
     *
     * @param reserve3 the value for t_qm_templatedetail.RESERVE_3
     *
     * @mbg.generated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.RESERVE_4
     *
     * @return the value of t_qm_templatedetail.RESERVE_4
     *
     * @mbg.generated
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.RESERVE_4
     *
     * @param reserve4 the value for t_qm_templatedetail.RESERVE_4
     *
     * @mbg.generated
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_qm_templatedetail.RESERVE_5
     *
     * @return the value of t_qm_templatedetail.RESERVE_5
     *
     * @mbg.generated
     */
    public String getReserve5() {
        return reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_qm_templatedetail.RESERVE_5
     *
     * @param reserve5 the value for t_qm_templatedetail.RESERVE_5
     *
     * @mbg.generated
     */
    public void setReserve5(String reserve5) {
        this.reserve5 = reserve5 == null ? null : reserve5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_templatedetail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", nodeId=").append(nodeId);
        sb.append(", nodeType=").append(nodeType);
        sb.append(", templateId=").append(templateId);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", cityId=").append(cityId);
        sb.append(", nodeName=").append(nodeName);
        sb.append(", pNodeId=").append(pNodeId);
        sb.append(", nodeStruct=").append(nodeStruct);
        sb.append(", minusScore=").append(minusScore);
        sb.append(", deductRange=").append(deductRange);
        sb.append(", remark=").append(remark);
        sb.append(", nodeOrder=").append(nodeOrder);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", modfTime=").append(modfTime);
        sb.append(", oprStaffId=").append(oprStaffId);
        sb.append(", createStaffId=").append(createStaffId);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", percScore=").append(percScore);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", reserve3=").append(reserve3);
        sb.append(", reserve4=").append(reserve4);
        sb.append(", reserve5=").append(reserve5);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}