package mapper;

import com.busy.model.AuthPermission;
import java.util.List;

public interface AuthPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    int insert(AuthPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    AuthPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    List<AuthPermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthPermission record);
}