package mapper;

import com.busy.model.AuthGroupPermissions;
import java.util.List;

public interface AuthGroupPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_permissions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_permissions
     *
     * @mbg.generated
     */
    int insert(AuthGroupPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_permissions
     *
     * @mbg.generated
     */
    AuthGroupPermissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_permissions
     *
     * @mbg.generated
     */
    List<AuthGroupPermissions> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_group_permissions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthGroupPermissions record);
}