package mapper;

import com.busy.model.DjangoSession;
import java.util.List;

public interface DjangoSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sessionKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_session
     *
     * @mbg.generated
     */
    int insert(DjangoSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_session
     *
     * @mbg.generated
     */
    DjangoSession selectByPrimaryKey(String sessionKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_session
     *
     * @mbg.generated
     */
    List<DjangoSession> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DjangoSession record);
}