package mapper;

import com.busy.model.DjangoContentType;
import java.util.List;

public interface DjangoContentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_content_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_content_type
     *
     * @mbg.generated
     */
    int insert(DjangoContentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_content_type
     *
     * @mbg.generated
     */
    DjangoContentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_content_type
     *
     * @mbg.generated
     */
    List<DjangoContentType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table django_content_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DjangoContentType record);
}