package mapper;

import com.busy.model.TQmTransChangeRecord;
import java.util.List;

public interface TQmTransChangeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    int insert(TQmTransChangeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    TQmTransChangeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    List<TQmTransChangeRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_qm_trans_change_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TQmTransChangeRecord record);
}